#include "behaviordetector.h"
#include <iostream>
#include <fstream>
#include <chrono>
#include <iomanip>
#include <sstream>

using namespace cv;
using namespace cv::dnn;
using namespace std;

// ============================================================================
// CONSTRUCTOR
// ============================================================================
BehaviorDetector::BehaviorDetector(const string& model_path, int size, float conf_th, float nms_th) 
    : input_size(size), conf_threshold(conf_th), nms_threshold(nms_th) 
{
    // Load the exported ONNX model into memory
    net = readNet(model_path);
    
    // CRITICAL: Must exactly match the alphabetical order generated by Roboflow
    class_names = {"distraction", "drowsy", "eyeclose", "face", "phone", "smoking", "yawn"};
    log_file = "train_dms_log.txt";
}

// ============================================================================
// HELPER: DYNAMIC THRESHOLDS
// ============================================================================
float BehaviorDetector::getClassThreshold(int class_id) {
    // Return specific confidence thresholds based on the object's characteristics.
    // Small objects (eyeclose) need lower thresholds to be detected.
    switch (class_id) {
        case 0: return 0.30f; // distraction
        case 1: return 0.25f; // drowsy
        case 2: return 0.40f; // eyeclose
        case 3: return 0.30f; // face
        case 4: return 0.30f; // phone
        case 5: return 0.20f; // smoking
        case 6: return 0.20f; // yawn
        default: return 0.25f;
    }
}

// ============================================================================
// HELPER: AUDIT LOGGING
// ============================================================================
void BehaviorDetector::logAndPrint(const string& behavior, float conf) {
    // Generate a human-readable timestamp
    auto now = chrono::system_clock::now();
    time_t tt = chrono::system_clock::to_time_t(now);
    tm local_tm = *localtime(&tt);
    stringstream ss;
    ss << put_time(&local_tm, "%Y-%m-%d %H:%M:%S") << " | EVENT | " << behavior
       << " | conf: " << fixed << setprecision(3) << conf << endl;
    
    string line = ss.str();
    cout << line; // Print to terminal for real-time monitoring
    
    // Append securely to the text log file
    ofstream logfile(log_file, ios::app);
    if (logfile.is_open()) {
        logfile << line;
        logfile.close();
    }
}

// ============================================================================
// STEP 1: PREPROCESSING (LETTERBOX)
// ============================================================================
Mat BehaviorDetector::letterbox(const Mat& source) {
    // Scale the image while preserving the original aspect ratio to prevent distortion.
    float scale = min((float)input_size / source.cols, (float)input_size / source.rows);
    int new_w = source.cols * scale;
    int new_h = source.rows * scale;

    Mat resized;
    resize(source, resized, Size(new_w, new_h));

    // Calculate the remaining empty space and divide by 2 to center the image.
    int pad_w = input_size - new_w;
    int pad_h = input_size - new_h;

    int top = pad_h / 2;
    int bottom = pad_h - top;
    int left = pad_w / 2;
    int right = pad_w - left;

    // Fill the empty padding space with gray color (114) which YOLO expects.
    Mat result;
    copyMakeBorder(resized, result, top, bottom, left, right, BORDER_CONSTANT, Scalar(114, 114, 114));
    return result;
}

// ============================================================================
// STEP 2: POSTPROCESSING (TENSOR PARSING & NMS)
// ============================================================================
vector<Detection> BehaviorDetector::postprocess(const vector<Mat>& outputs, const Size& frame_size) {
    vector<Detection> detections;
    if (outputs.empty()) return detections;

    Mat output = outputs[0];
    
    // YOLOv8 natively outputs a 3D tensor: [batch, features, predictions].
    // We transpose it to a 2D matrix [predictions, features] to easily loop through it.
    if (output.dims == 3) {
        Mat output2d(output.size[1], output.size[2], CV_32F, output.ptr<float>());
        Mat transposed; 
        cv::transpose(output2d, transposed); 
        output = transposed; 
    }

    int num_classes = output.cols - 4; // First 4 columns are cx, cy, w, h
    vector<Rect> boxes;
    vector<float> confidences;
    vector<int> class_ids;

    // Recalculate scaling to map the bounding boxes back to the original camera resolution
    float scale = min((float)input_size / frame_size.width, (float)input_size / frame_size.height);
    int pad_w = (input_size - frame_size.width * scale) / 2;
    int pad_h = (input_size - frame_size.height * scale) / 2;

    // Loop through all anchor predictions
    for (int i = 0; i < output.rows; ++i) {
        Mat row = output.row(i);
        Mat scores = row.colRange(4, 4 + num_classes);

        // Find the class index with the highest probability score
        Point class_id_pt;
        double max_class_score;
        minMaxLoc(scores, nullptr, &max_class_score, nullptr, &class_id_pt);

        float obj_conf = static_cast<float>(max_class_score);
        
        // Filter out weak predictions immediately
        if (obj_conf > getClassThreshold(class_id_pt.x)) {
            float cx = row.at<float>(0);
            float cy = row.at<float>(1);
            float w  = row.at<float>(2);
            float h  = row.at<float>(3);

            // Convert Center X/Y to Top-Left X/Y and strip the letterbox padding
            int left   = static_cast<int>((cx - w / 2.0f - pad_w) / scale);
            int top    = static_cast<int>((cy - h / 2.0f - pad_h) / scale);
            int width  = static_cast<int>(w / scale);
            int height = static_cast<int>(h / scale);

            boxes.emplace_back(left, top, width, height);
            confidences.push_back(obj_conf);
            class_ids.push_back(class_id_pt.x);
        }
    }

    // Apply Non-Maximum Suppression (NMS).
    // Uses an offset strategy to perform independent NMS per class (Multi-class NMS).
    vector<Rect> nms_boxes;
    int max_wh = 4096; 
    for (size_t i = 0; i < boxes.size(); i++) {
        int offset = class_ids[i] * max_wh;
        nms_boxes.push_back(Rect(boxes[i].x + offset, boxes[i].y + offset, boxes[i].width, boxes[i].height));
    }

    vector<int> indices;
    dnn::NMSBoxes(nms_boxes, confidences, conf_threshold, nms_threshold, indices);

    // Save final survived boxes into the struct
    for (int idx : indices) {
        if (class_ids[idx] >= 0 && class_ids[idx] < static_cast<int>(class_names.size())) {
            detections.push_back({class_ids[idx], confidences[idx], boxes[idx]});
        }
    }
    return detections;
}

// ============================================================================
// STEP 3: DEBOUNCE AND BUSINESS LOGIC
// ============================================================================
void BehaviorDetector::updateAlarmLogic(const vector<Detection>& detections) {
    // Reset flags for the current frame
    bool found_driver = false; 
    bool found_distracted = false;
    bool found_phone = false;
    bool found_sleepy = false;
    bool found_smoking = false;

    // Scan through all valid detections in this frame
    for (const auto& det : detections) {
        const string& behavior = class_names[det.class_id];
        
        // If the AI sees anything from our dataset, it means the driver is in the seat.
        found_driver = true;

        if (behavior == "distraction") found_distracted = true;
        if (behavior == "phone") found_phone = true;
        if (behavior == "smoking") found_smoking = true;
        // Group micro-expressions (eyes closed, yawning) into the overarching "Sleepy" state.
        if (behavior == "eyeclose" || behavior == "yawn" || behavior == "drowsy") {
            found_sleepy = true;
        }
    }

    // --- State Machine Execution ---
    // Rule: Increment counter if behavior exists. Reset to 0 if behavior stops.
    // Trigger alarm ONLY when the counter exceeds the defined THRESHOLD.

    if (!found_driver) {
        if (++consecutive_no_face >= NO_FACE_ALARM_FRAMES && !is_no_face) {
            logAndPrint("ALARM: NO DRIVER DETECTED", 1.0);
            is_no_face = true;
        }
    } else { consecutive_no_face = 0; is_no_face = false; }

    if (found_distracted) {
        if (++consecutive_distracted >= DISTRACTED_ALARM_FRAMES && !is_distracted) {
            logAndPrint("ALARM: DRIVER DISTRACTED", 1.0);
            is_distracted = true;
        }
    } else { consecutive_distracted = 0; is_distracted = false; }

    if (found_phone) {
        if (++consecutive_phone >= PHONE_ALARM_FRAMES && !is_using_phone) {
            logAndPrint("ALARM: ILLEGAL PHONE USAGE", 1.0);
            is_using_phone = true;
        }
    } else { consecutive_phone = 0; is_using_phone = false; }

    if (found_sleepy) {
        if (++consecutive_sleepy >= SLEEPY_ALARM_FRAMES && !is_sleepy) {
            logAndPrint("ALARM: CRITICAL - DROWSY/SLEEPING", 1.0);
            is_sleepy = true;
        }
    } else { consecutive_sleepy = 0; is_sleepy = false; }

    if (found_smoking) {
        if (++consecutive_smoking >= SMOKING_ALARM_FRAMES && !is_smoking) {
            logAndPrint("ALARM: SMOKING IN CABIN", 1.0);
            is_smoking = true;
        }
    } else { consecutive_smoking = 0; is_smoking = false; }
}

// ============================================================================
// STEP 4: UI RENDERING
// ============================================================================
void BehaviorDetector::renderVisuals(Mat& frame) {
    // Draw green bounding boxes and labels for the detected objects
    for (const auto& det : last_detections) {
        const string& behavior = class_names[det.class_id];
        rectangle(frame, det.box, Scalar(0, 255, 0), 1);
        string label = behavior + " " + to_string(det.confidence).substr(0, 4);
        putText(frame, label, Point(det.box.x, det.box.y - 10),
                FONT_HERSHEY_SIMPLEX, 0.6, Scalar(0, 255, 0), 1);
    }

    // Draw red/orange overlay texts if alarms are currently active
    int y_pos = 50; 
    if (is_no_face) {
        putText(frame, "WARNING: NO DRIVER!!!", Point(30, y_pos), FONT_HERSHEY_SIMPLEX, 1.2, Scalar(0, 0, 255), 3);
        y_pos += 40;
    }
    if (is_distracted) {
        putText(frame, "WARNING: DISTRACTED!!!", Point(30, y_pos), FONT_HERSHEY_SIMPLEX, 1.2, Scalar(0, 165, 255), 3);
        y_pos += 40;
    }
    if (is_using_phone) {
        putText(frame, "WARNING: PHONE USAGE!!!", Point(30, y_pos), FONT_HERSHEY_SIMPLEX, 1.2, Scalar(255, 0, 0), 3);
        y_pos += 40;
    }
    if (is_sleepy) {
        putText(frame, "WARNING: DROWSY/SLEEPING!!!", Point(30, y_pos), FONT_HERSHEY_SIMPLEX, 1.2, Scalar(0, 0, 255), 3);
        y_pos += 40;
    }
    if (is_smoking) {
        putText(frame, "WARNING: SMOKING!!!", Point(30, y_pos), FONT_HERSHEY_SIMPLEX, 1.2, Scalar(0, 255, 255), 3);
    }
}

// ============================================================================
// MAIN PROCESSING PIPELINE
// ============================================================================
void BehaviorDetector::processFrame(Mat& frame, bool run_inference) {
    if (run_inference) {
        // Step A: Format image for YOLO
        Mat letterboxed = letterbox(frame);
        
        // Step B: Create a 4D blob and normalize pixel values to [0, 1] range
        Mat blob = blobFromImage(letterboxed, 1.0 / 255.0, Size(input_size, input_size), Scalar(0,0,0), true, false);
        net.setInput(blob);
        
        // Step C: Run Neural Network Forward Pass
        vector<Mat> outputs;
        net.forward(outputs, net.getUnconnectedOutLayersNames());
        
        // Step D: Parse Tensor -> Extract Rectangles -> Apply Debounce Logic
        last_detections = postprocess(outputs, frame.size());
        updateAlarmLogic(last_detections);
    }
    
    // Step E: Draw on the frame (Executes every frame to keep video smooth)
    renderVisuals(frame);
}
